# This CI will run after publish a new release

name: Push to Other Repo and Make a PR

on: 
  release:
    types: [published]
  
jobs:
  processing_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push then create PR
        uses: sepulsa/push_then_pr@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_INTEGRATED_REPO }}

            DEST_GITHUB_USERNAME: 'hohoabhi'
            DEST_REPO_NAME: 'knowledge-base'
            USER_EMAIL: ''
            PUSH_TO_BRANCH: 'docs-system-doc'
            PR_TO_BRANCH: 'master'
            # You can add multiple source file or folder separate by space
            SRC_DIR: 'docs/*' 
            # You can create nested folder
            DEST_DIR: 'System-Documents/system-doc'
            # You can rename with format source(comma)target
            # Multiple line if you want to move multiple file / folder
            # Add your custom Pull Request message
            PR_MESSAGE: 'New release from system_doc'
